### PR TITLE
fix(session): fix PROMPT_SQL unwrap

### LINKED ISSUE #261: loading auto complete keywords failed
> loading auto complete keywords failed: APIError: ResponseError with 2601: , cause: failed to decode Protobuf message: buffer underflow
(while get UDFs).

### PR DESCRIPTION
**Pull request by sundy-li**
fix PROMPT_SQL unwrap error

fixes #261

### CODE REVIEW

**Review by everpcpc — APPROVED** [review]

File: cli/tests/http/05-stream.sh [hunk 1]
```diff
@@ -0,0 +1,27 @@
+#!/bin/bash
+## uncomment these when QUERY_DATABEND_ENTERPRISE_LICENSE env is set
```
Comment (everpcpc) [inline cli/tests/http/05-stream.sh:2]: I will do it later
